DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burgers(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
eaten BOOLEAN NOT NULL DEFAULT false,
PRIMARY KEY ( id )
);